default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: message_me_development

test:
  <<: *default
  database: message_me_test

production:
  <<: *default
  database: message_me_production
  username:  message_me 
  password: <%= ENV["TESTPROJECT_DATABASE_PASSWORD"] %>


